# Generated by Django 5.0.2 on 2024-07-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_docente', '0002_remove_tramite_gestor_delete_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='carrera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
