# Generated by Django 5.0.2 on 2024-07-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_docente', '0003_alter_tramite_carrera_alter_tramite_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
