# Generated by Django 5.0.2 on 2025-06-04 22:06

import plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_alter_noticias_imagen_cabecera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='Noticias/04-06-2025/', validators=[plataforma.models.validate_file_extension]),
        ),
    ]
