# Generated by Django 5.0.2 on 2025-04-29 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0009_alter_noticias_imagen_cabecera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('tramitegeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plataforma.tramitegeneral')),
                ('document', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('plataforma.tramitegeneral',),
        ),
        migrations.CreateModel(
            name='FeedingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.IntegerField()),
                ('lunch', models.IntegerField()),
                ('dinner', models.IntegerField()),
                ('snack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1)),
                ('identification', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='MaintancePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaintanceProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransportProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationProcedure',
            fields=[
                ('procedure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internal_procedures.procedure')),
                ('accommodation_type', models.CharField(choices=[('A', 'Instalaciones Hoteleras'), ('B', 'Hotelito de posgrado de la UHO')], max_length=1)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('description', models.TextField()),
                ('feeding_days', models.ManyToManyField(to='internal_procedures.feedingdays')),
                ('guests', models.ManyToManyField(to='internal_procedures.guest')),
            ],
            bases=('internal_procedures.procedure',),
        ),
        migrations.CreateModel(
            name='FeedingProcedure',
            fields=[
                ('procedure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internal_procedures.procedure')),
                ('feeding_type', models.CharField(choices=[('A', 'Restaurante Especializado'), ('B', 'Hotelito de posgrado de la UHO')], max_length=1)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('description', models.TextField()),
                ('ammount', models.IntegerField()),
                ('feeding_days', models.ManyToManyField(to='internal_procedures.feedingdays')),
            ],
            bases=('internal_procedures.procedure',),
        ),
        migrations.CreateModel(
            name='MaintenanceProcedure',
            fields=[
                ('procedure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internal_procedures.procedure')),
                ('description', models.TextField()),
                ('picture', models.BinaryField()),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal_procedures.maintancepriority')),
                ('procedure_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal_procedures.maintanceproceduretype')),
            ],
            bases=('internal_procedures.procedure',),
        ),
        migrations.CreateModel(
            name='TransportProcedure',
            fields=[
                ('procedure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='internal_procedures.procedure')),
                ('departure_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('departure_place', models.CharField(max_length=150)),
                ('return_place', models.CharField(max_length=150)),
                ('passengers', models.IntegerField()),
                ('description', models.TextField()),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('procedure_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal_procedures.transportproceduretype')),
            ],
            bases=('internal_procedures.procedure',),
        ),
    ]
