# Generated by Django 5.0.2 on 2025-05-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceProcedure',
            new_name='MaintanceProcedure',
        ),
    ]
