# Generated by Django 5.0.2 on 2025-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0002_rename_maintenanceprocedure_maintanceprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='state',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintanceprocedure',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
