# Generated by Django 5.0.2 on 2025-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0003_procedure_state_alter_maintanceprocedure_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintanceprocedure',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
