# Generated by Django 5.0.2 on 2025-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0004_alter_maintanceprocedure_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='state',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('EN PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
