# Generated by Django 5.0.2 on 2025-05-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0006_area_department_alter_procedure_state_procedure_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_procedures.area'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_procedures.department'),
        ),
    ]
