# Generated by Django 5.0.2 on 2025-05-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0007_alter_procedure_area_alter_procedure_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='internal_procedures.note'),
        ),
    ]
