# Generated by Django 5.0.2 on 2025-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0008_note_procedure_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.ManyToManyField(blank=True, to='internal_procedures.note'),
        ),
    ]
