# Generated by Django 5.0.2 on 2025-05-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0010_alter_procedure_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.ManyToManyField(to='internal_procedures.note'),
        ),
    ]
