# Generated by Django 5.0.2 on 2025-05-25 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_procedures', '0011_alter_procedure_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internal_procedures.area'),
        ),
        migrations.AddField(
            model_name='transportprocedure',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accommodationprocedure',
            name='feeding_days',
            field=models.ManyToManyField(blank=True, null=True, to='internal_procedures.feedingdays'),
        ),
    ]
