# Generated by Django 5.0.2 on 2024-09-06 14:27

import atencion_poblacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_poblacion', '0009_alter_atencionpoblacion_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionpoblacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='AtencionPoblacion/06-09-2024/', validators=[atencion_poblacion.models.validate_file_extension]),
        ),
    ]
