<<<<<<< HEAD
# Generated by Django 5.0.2 on 2025-05-27 15:01
=======
# Generated by Django 5.0.2 on 2025-05-18 12:07
>>>>>>> ae80041f6b4af1725b4848149f41259572c04152

import atencion_poblacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_poblacion', '0012_alter_atencionpoblacion_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionpoblacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='AtencionPoblacion/18-05-2025/', validators=[atencion_poblacion.models.validate_file_extension]),
        ),
    ]
