# Generated by Django 5.0.2 on 2025-06-04 22:06

import atencion_poblacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_poblacion', '0013_alter_atencionpoblacion_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionpoblacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='AtencionPoblacion/04-06-2025/', validators=[atencion_poblacion.models.validate_file_extension]),
        ),
    ]
